name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 2.0.0

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: 
    git: 
      url: https://github.com/syan-park/dio.git 
      path: dio
      version: ^4.0.0
  source_gen: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0 
  retrofit:
    path: ../annotation
  analyzer: ^1.5.0
  dart_style: ^2.0.1
  build: ^2.0.1

dev_dependencies:
  test: 1.17.2
  source_gen_test: ^1.0.0 